export type CountryZone = { label: string; zone: string };

export const COUNTRY_TIMEZONES: CountryZone[] = [
  { label: "Afghanistan", zone: "Asia/Kabul" },
  { label: "Albania", zone: "Europe/Tirane" },
  { label: "Algeria", zone: "Africa/Algiers" },
  { label: "Andorra", zone: "Europe/Andorra" },
  { label: "Angola", zone: "Africa/Luanda" },
  { label: "Argentina", zone: "America/Argentina/Buenos_Aires" },
  { label: "Armenia", zone: "Asia/Yerevan" },
  { label: "Australia — Eastern", zone: "Australia/Sydney" },
  { label: "Australia — Central", zone: "Australia/Adelaide" },
  { label: "Australia — Western", zone: "Australia/Perth" },
  { label: "Austria", zone: "Europe/Vienna" },
  { label: "Azerbaijan", zone: "Asia/Baku" },
  { label: "Bahamas", zone: "America/Nassau" },
  { label: "Bahrain", zone: "Asia/Bahrain" },
  { label: "Bangladesh", zone: "Asia/Dhaka" },
  { label: "Barbados", zone: "America/Barbados" },
  { label: "Belarus", zone: "Europe/Minsk" },
  { label: "Belgium", zone: "Europe/Brussels" },
  { label: "Belize", zone: "America/Belize" },
  { label: "Benin", zone: "Africa/Porto-Novo" },
  { label: "Bhutan", zone: "Asia/Thimphu" },
  { label: "Bolivia", zone: "America/La_Paz" },
  { label: "Bosnia and Herzegovina", zone: "Europe/Sarajevo" },
  { label: "Botswana", zone: "Africa/Gaborone" },
  { label: "Brazil — Brasília", zone: "America/Sao_Paulo" },
  { label: "Brazil — Manaus", zone: "America/Manaus" },
  { label: "Brunei", zone: "Asia/Brunei" },
  { label: "Bulgaria", zone: "Europe/Sofia" },
  { label: "Burkina Faso", zone: "Africa/Ouagadougou" },
  { label: "Burundi", zone: "Africa/Bujumbura" },
  { label: "Cambodia", zone: "Asia/Phnom_Penh" },
  { label: "Cameroon", zone: "Africa/Douala" },
  { label: "Canada — Eastern", zone: "America/Toronto" },
  { label: "Canada — Central", zone: "America/Winnipeg" },
  { label: "Canada — Mountain", zone: "America/Edmonton" },
  { label: "Canada — Pacific", zone: "America/Vancouver" },
  { label: "Canada — Atlantic", zone: "America/Halifax" },
  { label: "Cape Verde", zone: "Atlantic/Cape_Verde" },
  { label: "Central African Republic", zone: "Africa/Bangui" },
  { label: "Chad", zone: "Africa/Ndjamena" },
  { label: "Chile", zone: "America/Santiago" },
  { label: "China", zone: "Asia/Shanghai" },
  { label: "Colombia", zone: "America/Bogota" },
  { label: "Comoros", zone: "Indian/Comoro" },
  { label: "Costa Rica", zone: "America/Costa_Rica" },
  { label: "Croatia", zone: "Europe/Zagreb" },
  { label: "Cuba", zone: "America/Havana" },
  { label: "Cyprus", zone: "Asia/Nicosia" },
  { label: "Czech Republic", zone: "Europe/Prague" },
  { label: "Denmark", zone: "Europe/Copenhagen" },
  { label: "Djibouti", zone: "Africa/Djibouti" },
  { label: "Dominican Republic", zone: "America/Santo_Domingo" },
  { label: "Ecuador", zone: "America/Guayaquil" },
  { label: "Egypt", zone: "Africa/Cairo" },
  { label: "El Salvador", zone: "America/El_Salvador" },
  { label: "Equatorial Guinea", zone: "Africa/Malabo" },
  { label: "Eritrea", zone: "Africa/Asmara" },
  { label: "Estonia", zone: "Europe/Tallinn" },
  { label: "Eswatini", zone: "Africa/Mbabane" },
  { label: "Ethiopia", zone: "Africa/Addis_Ababa" },
  { label: "Fiji", zone: "Pacific/Fiji" },
  { label: "Finland", zone: "Europe/Helsinki" },
  { label: "France", zone: "Europe/Paris" },
  { label: "Gabon", zone: "Africa/Libreville" },
  { label: "Gambia", zone: "Africa/Banjul" },
  { label: "Georgia", zone: "Asia/Tbilisi" },
  { label: "Germany", zone: "Europe/Berlin" },
  { label: "Ghana", zone: "Africa/Accra" },
  { label: "Greece", zone: "Europe/Athens" },
  { label: "Guatemala", zone: "America/Guatemala" },
  { label: "Guinea", zone: "Africa/Conakry" },
  { label: "Guinea-Bissau", zone: "Africa/Bissau" },
  { label: "Guyana", zone: "America/Guyana" },
  { label: "Haiti", zone: "America/Port-au-Prince" },
  { label: "Honduras", zone: "America/Tegucigalpa" },
  { label: "Hong Kong", zone: "Asia/Hong_Kong" },
  { label: "Hungary", zone: "Europe/Budapest" },
  { label: "Iceland", zone: "Atlantic/Reykjavik" },
  { label: "India", zone: "Asia/Kolkata" },
  { label: "Indonesia — Jakarta", zone: "Asia/Jakarta" },
  { label: "Iran", zone: "Asia/Tehran" },
  { label: "Iraq", zone: "Asia/Baghdad" },
  { label: "Ireland", zone: "Europe/Dublin" },
  { label: "Israel", zone: "Asia/Jerusalem" },
  { label: "Italy", zone: "Europe/Rome" },
  { label: "Ivory Coast", zone: "Africa/Abidjan" },
  { label: "Jamaica", zone: "America/Jamaica" },
  { label: "Japan", zone: "Asia/Tokyo" },
  { label: "Jordan", zone: "Asia/Amman" },
  { label: "Kazakhstan", zone: "Asia/Almaty" },
  { label: "Kenya", zone: "Africa/Nairobi" },
  { label: "Kuwait", zone: "Asia/Kuwait" },
  { label: "Kyrgyzstan", zone: "Asia/Bishkek" },
  { label: "Laos", zone: "Asia/Vientiane" },
  { label: "Latvia", zone: "Europe/Riga" },
  { label: "Lebanon", zone: "Asia/Beirut" },
  { label: "Lesotho", zone: "Africa/Maseru" },
  { label: "Liberia", zone: "Africa/Monrovia" },
  { label: "Libya", zone: "Africa/Tripoli" },
  { label: "Liechtenstein", zone: "Europe/Vaduz" },
  { label: "Lithuania", zone: "Europe/Vilnius" },
  { label: "Luxembourg", zone: "Europe/Luxembourg" },
  { label: "Macau", zone: "Asia/Macau" },
  { label: "Madagascar", zone: "Indian/Antananarivo" },
  { label: "Malawi", zone: "Africa/Blantyre" },
  { label: "Malaysia", zone: "Asia/Kuala_Lumpur" },
  { label: "Maldives", zone: "Indian/Maldives" },
  { label: "Mali", zone: "Africa/Bamako" },
  { label: "Malta", zone: "Europe/Malta" },
  { label: "Mauritania", zone: "Africa/Nouakchott" },
  { label: "Mauritius", zone: "Indian/Mauritius" },
  { label: "Mexico", zone: "America/Mexico_City" },
  { label: "Moldova", zone: "Europe/Chisinau" },
  { label: "Monaco", zone: "Europe/Monaco" },
  { label: "Mongolia", zone: "Asia/Ulaanbaatar" },
  { label: "Montenegro", zone: "Europe/Podgorica" },
  { label: "Morocco", zone: "Africa/Casablanca" },
  { label: "Mozambique", zone: "Africa/Maputo" },
  { label: "Myanmar", zone: "Asia/Yangon" },
  { label: "Namibia", zone: "Africa/Windhoek" },
  { label: "Nepal", zone: "Asia/Katmandu" },
  { label: "Netherlands", zone: "Europe/Amsterdam" },
  { label: "New Zealand", zone: "Pacific/Auckland" },
  { label: "Nicaragua", zone: "America/Managua" },
  { label: "Niger", zone: "Africa/Niamey" },
  { label: "Nigeria", zone: "Africa/Lagos" },
  { label: "North Korea", zone: "Asia/Pyongyang" },
  { label: "North Macedonia", zone: "Europe/Skopje" },
  { label: "Norway", zone: "Europe/Oslo" },
  { label: "Oman", zone: "Asia/Muscat" },
  { label: "Pakistan", zone: "Asia/Karachi" },
  { label: "Panama", zone: "America/Panama" },
  { label: "Papua New Guinea", zone: "Pacific/Port_Moresby" },
  { label: "Paraguay", zone: "America/Asuncion" },
  { label: "Peru", zone: "America/Lima" },
  { label: "Philippines", zone: "Asia/Manila" },
  { label: "Poland", zone: "Europe/Warsaw" },
  { label: "Portugal", zone: "Europe/Lisbon" },
  { label: "Puerto Rico", zone: "America/Puerto_Rico" },
  { label: "Qatar", zone: "Asia/Qatar" },
  { label: "Romania", zone: "Europe/Bucharest" },
  { label: "Russia — Moscow", zone: "Europe/Moscow" },
  { label: "Russia — Yekaterinburg", zone: "Asia/Yekaterinburg" },
  { label: "Russia — Novosibirsk", zone: "Asia/Novosibirsk" },
  { label: "Russia — Vladivostok", zone: "Asia/Vladivostok" },
  { label: "Rwanda", zone: "Africa/Kigali" },
  { label: "Saudi Arabia", zone: "Asia/Riyadh" },
  { label: "Senegal", zone: "Africa/Dakar" },
  { label: "Serbia", zone: "Europe/Belgrade" },
  { label: "Sierra Leone", zone: "Africa/Freetown" },
  { label: "Singapore", zone: "Asia/Singapore" },
  { label: "Slovakia", zone: "Europe/Bratislava" },
  { label: "Slovenia", zone: "Europe/Ljubljana" },
  { label: "Somalia", zone: "Africa/Mogadishu" },
  { label: "South Africa", zone: "Africa/Johannesburg" },
  { label: "South Korea", zone: "Asia/Seoul" },
  { label: "South Sudan", zone: "Africa/Juba" },
  { label: "Spain", zone: "Europe/Madrid" },
  { label: "Sri Lanka", zone: "Asia/Colombo" },
  { label: "Sudan", zone: "Africa/Khartoum" },
  { label: "Suriname", zone: "America/Paramaribo" },
  { label: "Sweden", zone: "Europe/Stockholm" },
  { label: "Switzerland", zone: "Europe/Zurich" },
  { label: "Syria", zone: "Asia/Damascus" },
  { label: "Taiwan", zone: "Asia/Taipei" },
  { label: "Tajikistan", zone: "Asia/Dushanbe" },
  { label: "Tanzania", zone: "Africa/Dar_es_Salaam" },
  { label: "Thailand", zone: "Asia/Bangkok" },
  { label: "Togo", zone: "Africa/Lome" },
  { label: "Trinidad and Tobago", zone: "America/Port_of_Spain" },
  { label: "Tunisia", zone: "Africa/Tunis" },
  { label: "Turkey", zone: "Europe/Istanbul" },
  { label: "Turkmenistan", zone: "Asia/Ashgabat" },
  { label: "Uganda", zone: "Africa/Kampala" },
  { label: "Ukraine", zone: "Europe/Kiev" },
  { label: "United Arab Emirates", zone: "Asia/Dubai" },
  { label: "United Kingdom", zone: "Europe/London" },
  { label: "United States — Eastern", zone: "America/New_York" },
  { label: "United States — Central", zone: "America/Chicago" },
  { label: "United States — Mountain", zone: "America/Denver" },
  { label: "United States — Pacific", zone: "America/Los_Angeles" },
  { label: "United States — Alaska", zone: "America/Anchorage" },
  { label: "United States — Hawaii", zone: "Pacific/Honolulu" },
  { label: "Uruguay", zone: "America/Montevideo" },
  { label: "Uzbekistan", zone: "Asia/Tashkent" },
  { label: "Venezuela", zone: "America/Caracas" },
  { label: "Vietnam", zone: "Asia/Ho_Chi_Minh" },
  { label: "Yemen", zone: "Asia/Aden" },
  { label: "Zambia", zone: "Africa/Lusaka" },
  { label: "Zimbabwe", zone: "Africa/Harare" },
].sort((a, b) => a.label.localeCompare(b.label));

export function utcOffsetLabel(zone: string, at: Date = new Date()) {
  try {
    const parts = new Intl.DateTimeFormat("en-US", { timeZone: zone, timeZoneName: "shortOffset" }).formatToParts(at);
    const raw = parts.find((p) => p.type === "timeZoneName")?.value || "";
    return raw.replace(/^GMT/, "UTC");
  } catch {
    return "";
  }
}
